#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Event_Management.Resource", IsApplication=true)]

namespace Event_Management
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::Event_Management.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::Event_Management.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::Event_Management.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::Event_Management.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::Event_Management.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::Event_Management.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::Event_Management.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::Event_Management.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::Event_Management.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::Event_Management.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::Event_Management.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::Event_Management.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::Event_Management.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::Event_Management.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::Event_Management.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::Event_Management.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::Event_Management.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::Event_Management.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::Event_Management.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::Event_Management.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::Event_Management.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::Event_Management.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::Event_Management.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::Event_Management.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::Event_Management.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::Event_Management.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::Event_Management.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::Event_Management.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::Event_Management.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::Event_Management.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int fab_material_blue_500 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int my_blue = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int my_gray = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int my_green = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int my_purple = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int fab_elevation_lollipop = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int fab_scroll_threshold = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int fab_shadow_size = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_size_mini = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_size_normal = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int datePicker1 = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int descriptionText = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int eventListView = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int fab = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView2 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView3 = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int titleText = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EventAdd = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
